"""create stg_eonet events

Revision ID: <71fcc8f3c61b>
Revises: <742edf9d51dd>
Create Date: <auto-generated>
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "71fcc8f3c61b"
down_revision: Union[str, Sequence[str], None] = "742edf9d51dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True, nullable=False),

        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("closed", sa.DateTime(timezone=True), nullable=True),

        sa.Column("categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=True),

        sa.Column("s_ingested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("s_source_url", sa.Text(), nullable=False),
        sa.Column("s_run_id", sa.BigInteger(), nullable=False),
        sa.Column("s_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),

        sa.ForeignKeyConstraint(["s_run_id"], ["tech.run_management.s_run_id"], ondelete="CASCADE"),
        sa.UniqueConstraint("event_id", "s_run_id", name="uq_stg_eonet_events_event_id_run_id"),
        schema="stg_eonet",
    )

    op.create_index(
        "ix_stg_eonet_events_event_id",
        "events",
        ["event_id"],
        unique=False,
        schema="stg_eonet",
    )

    op.create_index(
        "ix_stg_eonet_events_s_run_id",
        "events",
        ["s_run_id"],
        unique=False,
        schema="stg_eonet",
    )


def downgrade() -> None:
    op.drop_index("ix_stg_eonet_events_s_run_id", table_name="events", schema="stg_eonet")
    op.drop_index("ix_stg_eonet_events_event_id", table_name="events", schema="stg_eonet")
    op.drop_table("events", schema="stg_eonet")