"""drop public ingestion_runs

Revision ID: <new_revision_id>
Revises: aab03d729788
Create Date: <auto-generated>
"""
from typing import Sequence, Union

from alembic import op


revision: str = "742edf9d51dd"
down_revision: Union[str, Sequence[str], None] = "aab03d729788"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table("ingestion_runs")


def downgrade() -> None:
    raise NotImplementedError("Downgrade not implemented for dropping ingestion_runs")